### ISSUE TITLE
vagrant does not start

### ISSUE THREAD

**Issue by PolynomialDivision** [lborgav/vagrant-prosody#1]
Hey, something does not work. I followed the steps in thr README.md, but `vagrant up` gives me this error:
> ==> prosody: Running provisioner: ansible...
> Vagrant has automatically selected the compatibility mode '2.0'
> according to the Ansible version installed (2.9.7).
> 
> Alternatively, the compatibility mode can be specified in your Vagrantfile:
> https://www.vagrantup.com/docs/provisioning/ansible_common.html#compatibility_mode
> 
>     prosody: Running ansible-playbook...
> ERROR! conflicting action statements: service, sudo
> 
> The error appears to be in '.../vagrant-prosody/provisioning/roles/prosody/handlers/main.yml': line 3, column 3, but may
> be elsewhere in the file depending on the exact syntax problem.
> 
> The offending line appears to be:
> 
> 
> - name: reload prosody
>   ^ here
> Ansible failed to complete successfully. Any error output should be
> visible above. Please fix these errors and try again.
>

**Comment by lborgav** [comment]
It seems to be some issue on this ansible playbook. I't been a long time I'm not running Ansible so I'll take some days to fix it. 

Sorry
